# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "check"

[jobs]

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false


[jobs.check-watch]
command = ["cargo", "check", "--color", "always"]
need_stdout = false
watch = ["src"]

[jobs.test]
command = ["cargo", "nextest", "run", "--color", "always"]
need_stdout = true

[jobs.build-release]
command = ["cargo", "build", "--release"]
need_stdout = true

[keybindings]
space = "job:check"
t = "job:test"
r = "job:build-release"
w = "job:check-watch"