[package]
name = "ektox"
version = "0.1.0"
edition = "2021"
authors = ["Luca Xiang <luca.xiang@outlook.com>"]
categories = ["window64", "window-switcher", "application-launcher"]
description = "switch window with specify hotkey"

[dependencies]
